version: '3.2'

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 10s
      timeout: 5s
      retries: 3
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: nodejs_test
      MYSQL_USER: nodejs_test
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQLX: 'OFF'
    command: --pid-file=/run/mysqld/mysqld.pid
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-proot']
      timeout: 10s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-conf.d:/etc/mysql/conf.d
      - /app/node_modules
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - '8080:80'
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    links:
      - rabbitmq
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: nodejs_test
      DB_FLAVOUR: mysql
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTION_IV: ${ENCRYPTION_IV}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      RABBITMQ_HOST: 'amqp://rabbitmq:5672'
      RABBITMQ_EMAIL_QUEUE: 'emailQueue'
      NODEMAILER_HOST: 'smtp.gmail.com'
      NODEMAILER_PORT: 465
      NODEMAILER_USER: ${NODEMAILER_USER}
      NODEMAILER_PASSWORD: ${NODEMAILER_PASSWORD}
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
volumes:
  db_data:
  node_modules:
